# Uncomment the next line to define a global platform for your project
# platform :ios, '17.0'

target 'Wiki_Scanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wiki_Scanner

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'

end
